apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      lab: k8s-lab
  template:
    metadata:
      labels:
        lab: k8s-lab
    spec:
      containers:
      - name: recipe-container
        image: archerjb/my-recipe-api
        ports:
        - containerPort: 8080
